(cl:defpackage perception_stack_pkg-msg
  (:use )
  (:export
   "<BOUNDINGBOX>"
   "BOUNDINGBOX"
   "<DETECTIONLIST>"
   "DETECTIONLIST"
   "<FLOWFRAME>"
   "FLOWFRAME"
   "<PROCESSEDTRACKEDOBJECT>"
   "PROCESSEDTRACKEDOBJECT"
   "<PROCESSEDTRACKEDOBJECTSLIST>"
   "PROCESSEDTRACKEDOBJECTSLIST"
   "<TRACKEDOBJECT>"
   "TRACKEDOBJECT"
   "<TRACKEDOBJECTSLIST>"
   "TRACKEDOBJECTSLIST"
  ))

