// Generated by gencpp from file perception_stack_pkg/FlowFrame.msg
// DO NOT EDIT!


#ifndef PERCEPTION_STACK_PKG_MESSAGE_FLOWFRAME_H
#define PERCEPTION_STACK_PKG_MESSAGE_FLOWFRAME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace perception_stack_pkg
{
template <class ContainerAllocator>
struct FlowFrame_
{
  typedef FlowFrame_<ContainerAllocator> Type;

  FlowFrame_()
    : header()
    , height(0)
    , width(0)
    , flow_x()
    , flow_y()
    , dt(0.0)
    , scale_factor(0.0)  {
    }
  FlowFrame_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , height(0)
    , width(0)
    , flow_x(_alloc)
    , flow_y(_alloc)
    , dt(0.0)
    , scale_factor(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _height_type;
  _height_type height;

   typedef uint32_t _width_type;
  _width_type width;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _flow_x_type;
  _flow_x_type flow_x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _flow_y_type;
  _flow_y_type flow_y;

   typedef float _dt_type;
  _dt_type dt;

   typedef float _scale_factor_type;
  _scale_factor_type scale_factor;





  typedef boost::shared_ptr< ::perception_stack_pkg::FlowFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_stack_pkg::FlowFrame_<ContainerAllocator> const> ConstPtr;

}; // struct FlowFrame_

typedef ::perception_stack_pkg::FlowFrame_<std::allocator<void> > FlowFrame;

typedef boost::shared_ptr< ::perception_stack_pkg::FlowFrame > FlowFramePtr;
typedef boost::shared_ptr< ::perception_stack_pkg::FlowFrame const> FlowFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_stack_pkg::FlowFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_stack_pkg::FlowFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception_stack_pkg::FlowFrame_<ContainerAllocator1> & lhs, const ::perception_stack_pkg::FlowFrame_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.height == rhs.height &&
    lhs.width == rhs.width &&
    lhs.flow_x == rhs.flow_x &&
    lhs.flow_y == rhs.flow_y &&
    lhs.dt == rhs.dt &&
    lhs.scale_factor == rhs.scale_factor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception_stack_pkg::FlowFrame_<ContainerAllocator1> & lhs, const ::perception_stack_pkg::FlowFrame_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception_stack_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception_stack_pkg::FlowFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_stack_pkg::FlowFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_stack_pkg::FlowFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_stack_pkg::FlowFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_stack_pkg::FlowFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_stack_pkg::FlowFrame_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_stack_pkg::FlowFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8640e6324462ca9b9afc0877d3fce48";
  }

  static const char* value(const ::perception_stack_pkg::FlowFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8640e6324462ca9ULL;
  static const uint64_t static_value2 = 0xb9afc0877d3fce48ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_stack_pkg::FlowFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_stack_pkg/FlowFrame";
  }

  static const char* value(const ::perception_stack_pkg::FlowFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_stack_pkg::FlowFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint32 height\n"
"uint32 width\n"
"float32[] flow_x  \n"
"float32[] flow_y  \n"
"float32 dt        \n"
"float32 scale_factor  \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::perception_stack_pkg::FlowFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_stack_pkg::FlowFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.height);
      stream.next(m.width);
      stream.next(m.flow_x);
      stream.next(m.flow_y);
      stream.next(m.dt);
      stream.next(m.scale_factor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FlowFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_stack_pkg::FlowFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_stack_pkg::FlowFrame_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.width);
    s << indent << "flow_x[]" << std::endl;
    for (size_t i = 0; i < v.flow_x.size(); ++i)
    {
      s << indent << "  flow_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.flow_x[i]);
    }
    s << indent << "flow_y[]" << std::endl;
    for (size_t i = 0; i < v.flow_y.size(); ++i)
    {
      s << indent << "  flow_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.flow_y[i]);
    }
    s << indent << "dt: ";
    Printer<float>::stream(s, indent + "  ", v.dt);
    s << indent << "scale_factor: ";
    Printer<float>::stream(s, indent + "  ", v.scale_factor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_STACK_PKG_MESSAGE_FLOWFRAME_H
