// Generated by gencpp from file perception_stack_pkg/ProcessedTrackedObject.msg
// DO NOT EDIT!


#ifndef PERCEPTION_STACK_PKG_MESSAGE_PROCESSEDTRACKEDOBJECT_H
#define PERCEPTION_STACK_PKG_MESSAGE_PROCESSEDTRACKEDOBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception_stack_pkg
{
template <class ContainerAllocator>
struct ProcessedTrackedObject_
{
  typedef ProcessedTrackedObject_<ContainerAllocator> Type;

  ProcessedTrackedObject_()
    : id(0)
    , class_name()
    , speed(0.0)  {
    }
  ProcessedTrackedObject_(const ContainerAllocator& _alloc)
    : id(0)
    , class_name(_alloc)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_name_type;
  _class_name_type class_name;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator> const> ConstPtr;

}; // struct ProcessedTrackedObject_

typedef ::perception_stack_pkg::ProcessedTrackedObject_<std::allocator<void> > ProcessedTrackedObject;

typedef boost::shared_ptr< ::perception_stack_pkg::ProcessedTrackedObject > ProcessedTrackedObjectPtr;
typedef boost::shared_ptr< ::perception_stack_pkg::ProcessedTrackedObject const> ProcessedTrackedObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator1> & lhs, const ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.class_name == rhs.class_name &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator1> & lhs, const ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception_stack_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6cb3392170d89f5997df997b7d64b50";
  }

  static const char* value(const ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6cb3392170d89f5ULL;
  static const uint64_t static_value2 = 0x997df997b7d64b50ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_stack_pkg/ProcessedTrackedObject";
  }

  static const char* value(const ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"string class_name\n"
"float32 speed\n"
;
  }

  static const char* value(const ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.class_name);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProcessedTrackedObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_stack_pkg::ProcessedTrackedObject_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_name);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_STACK_PKG_MESSAGE_PROCESSEDTRACKEDOBJECT_H
