// Generated by gencpp from file perception_stack_pkg/TrackedObjectsList.msg
// DO NOT EDIT!


#ifndef PERCEPTION_STACK_PKG_MESSAGE_TRACKEDOBJECTSLIST_H
#define PERCEPTION_STACK_PKG_MESSAGE_TRACKEDOBJECTSLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <perception_stack_pkg/TrackedObject.h>

namespace perception_stack_pkg
{
template <class ContainerAllocator>
struct TrackedObjectsList_
{
  typedef TrackedObjectsList_<ContainerAllocator> Type;

  TrackedObjectsList_()
    : header()
    , TrackedObjectsList()  {
    }
  TrackedObjectsList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , TrackedObjectsList(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::perception_stack_pkg::TrackedObject_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::perception_stack_pkg::TrackedObject_<ContainerAllocator> >> _TrackedObjectsList_type;
  _TrackedObjectsList_type TrackedObjectsList;





  typedef boost::shared_ptr< ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator> const> ConstPtr;

}; // struct TrackedObjectsList_

typedef ::perception_stack_pkg::TrackedObjectsList_<std::allocator<void> > TrackedObjectsList;

typedef boost::shared_ptr< ::perception_stack_pkg::TrackedObjectsList > TrackedObjectsListPtr;
typedef boost::shared_ptr< ::perception_stack_pkg::TrackedObjectsList const> TrackedObjectsListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator1> & lhs, const ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.TrackedObjectsList == rhs.TrackedObjectsList;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator1> & lhs, const ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception_stack_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "811a223971dc616dee3b895ed3cdb809";
  }

  static const char* value(const ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x811a223971dc616dULL;
  static const uint64_t static_value2 = 0xee3b895ed3cdb809ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_stack_pkg/TrackedObjectsList";
  }

  static const char* value(const ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"TrackedObject[] TrackedObjectsList\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: perception_stack_pkg/TrackedObject\n"
"int32 x1 \n"
"int32 y1\n"
"int32 x2\n"
"int32 y2\n"
"int32 id\n"
"string class_name\n"
;
  }

  static const char* value(const ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.TrackedObjectsList);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackedObjectsList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_stack_pkg::TrackedObjectsList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "TrackedObjectsList[]" << std::endl;
    for (size_t i = 0; i < v.TrackedObjectsList.size(); ++i)
    {
      s << indent << "  TrackedObjectsList[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::perception_stack_pkg::TrackedObject_<ContainerAllocator> >::stream(s, indent + "    ", v.TrackedObjectsList[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_STACK_PKG_MESSAGE_TRACKEDOBJECTSLIST_H
